---
title: "Vignettev v1"
output: html_notebook
---


```{r}
install.packages("readr")
library(readr)
library(tidyverse)
install.packages("DataExplorer")
library(DataExplorer)
install.packages("mice")
library(mice)
install.packages("Hmisc")
library("Hmisc")

```

```{r}
data_path <- "/Users/virginiabaskin/Downloads/archive/MA_Public_Schools_2017.csv"
MAschools <- read_csv(data_path)
```
Definitely going to have to select columns to make a smaller dataframe, 302 fields is simply too many. 

Could do some kind of variable selection, but it makes much more sense for this first step to just chose the variables we have some interest in 

```{r}
maschools <- MAschools %>% select(`School Code`, `School Name`, `School Type`, Town, Zip, TOTAL_Enrollment, `First Language Not English`: `% Females`, `Average Class Size`, `Number of Students`, `Average Salary`, `% Graduated`, `% Still in School`, `Accountability and Assistance Level`: `District_Accountability and Assistance Description`)
maschools
```

```{r}
profile_missing(MAschools)
profile_missing(maschools)
```

```{r}
summary(maschools)
```

```{r}
md.pattern(maschools)

numMAschools <- maschools %>% select(TOTAL_Enrollment:`Average Salary`, `School Accountability Percentile (1-99)`)
#do we need % female and male?? 
cor(numMAschools, use="complete.obs")

```

```{r}
rcorr(as.matrix(numMAschools))
```

